version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: mediq_postgres
    environment:
      POSTGRES_USER: mediq
      POSTGRES_PASSWORD: mediq
      POSTGRES_DB: mediq
    ports:
      - "5432:5432"
    volumes:
      - mediq_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mediq" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: mediq_redis
    ports:
      - "6379:6379"
    volumes:
      - mediq_redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mediq_pgdata:
  mediq_redisdata:
